In [90]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies_ratings.csv')

In [6]:
df = df.drop(columns=['Harshita', 'Priya', 'Yukta'])

In [89]:
df

,Movies_Name,SandeepGiri,Abhishek,Gurkaran,Madhuri,Venu,Gurpreet,Sanket,Yukta,Supriyo,Stuti,Priya,Harshita,Gokul,Charan,Bhaskar,Ankit,Aakash,Prabha
0,Titanic,4.000000,2.000000,4.000000,5.00,4.000000,2.000000,4.0,3.892857,4,4.000000,3.892857,3.892857,4,5.0,3.892857,5,4.0,3.500000
1,Matrix,4.800000,1.000000,3.000000,5.00,4.500000,4.500000,4.0,3.792308,4,3.792308,3.792308,3.792308,4,3.0,3.792308,3,4.5,4.000000
2,Jurasic Park,4.200000,2.000000,4.000000,4.00,3.000000,4.000000,5.0,3.442857,3,3.000000,3.442857,3.442857,4,2.0,3.442857,2,4.0,4.000000
3,Sholay,4.000000,5.000000,4.000000,4.00,5.000000,3.000000,4.0,3.786667,4,3.000000,3.786667,3.786667,3,1.0,3.000000,5,5.0,3.800000
4,Dilwale Dulhania Le Jayenge,3.800000,5.000000,4.000000,2.00,4.000000,1.000000,4.0,3.320000,3,3.500000,3.320000,3.320000,3,3.0,1.000000,5,4.0,3.500000
5,Mughal-e-Azam,2.833333,2.000000,2.000000,5.00,4.000000,1.000000,3.0,2.833333,3,2.833333,2.833333,2.833333,3,2.0,1.000000,4,4.0,2.833333
6,Deewaar,2.958333,4.000000,2.000000,2.00,3.000000,1.000000,3.0,2.958333,3,3.000000,2.958333,2.958333,3,4.0,2.958333,4,3.5,2.958333
7,Amar Akbar Anthony,3.076923,5.000000,2.000000,2.00,4.000000,2.000000,3.0,3.076923,3,3.000000,3.076923,3.076923,3,3.0,2.000000,4,4.0,3.076923
8,Lagaan,4.000000,5.000000,3.000000,4.00,5.000000,4.000000,5.0,4.000000,3,4.000000,4.000000,4.000000,3,5.0,2.000000,4,5.0,4.000000
9,Kabhi Khushi Kabhie Gham,3.800000,4.000000,3.000000,2.00,5.000000,3.000000,4.0,3.153333,2,4.000000,3.153333,3.153333,2,3.0,2.000000,3,3.0,3.500000
10,Kal Ho Naa Ho,3.800000,3.000000,3.000000,2.00,4.000000,2.000000,4.0,3.113333,2,4.000000,3.113333,3.113333,4,2.0,1.000000,3,5.0,3.900000
11,3 Idiots,4.000000,5.000000,4.000000,4.50,5.000000,4.000000,5.0,4.433333,4,5.000000,4.433333,4.433333,5,3.0,4.000000,5,5.0,4.000000
12,Dabangg,2.923077,3.000000,3.000000,2.00,5.000000,3.000000,3.0,2.923077,3,3.000000,2.923077,2.923077,4,4.0,1.000000,1,3.0,2.923077
13,Zindagi Na Milegi Dobara,4.000000,3.000000,4.000000,4.00,4.000000,4.500000,4.0,4.000000,3,5.000000,4.000000,4.000000,5,5.0,3.000000,3,4.5,4.000000
14,Barfi!,3.700000,3.000000,4.000000,4.00,3.000000,2.000000,3.0,3.121429,3,3.000000,3.121429,3.121429,3,3.0,3.000000,3,3.0,3.121429
15,Yeh Jawaani Hai Deewani,3.350000,3.000000,3.350000,3.00,4.000000,4.000000,3.0,3.350000,3,5.000000,3.350000,3.350000,5,3.2,1.000000,1,5.0,3.350000
16,PK,4.000000,4.000000,4.500000,3.00,3.000000,2.000000,3.0,3.257143,3,4.000000,3.257143,3.257143,4,4.1,1.000000,2,4.0,3.257143
17,Bajrangi Bhaijaan,2.653846,4.000000,3.000000,2.00,4.000000,1.000000,3.0,2.653846,3,3.000000,2.653846,2.653846,3,3.5,1.000000,1,3.0,2.653846
18,Dangal,4.069231,5.000000,4.000000,3.00,5.000000,4.000000,4.0,4.069231,4,5.000000,4.069231,4.069231,5,3.9,3.000000,2,5.0,4.069231
19,Padmaavat,2.445455,2.445455,2.445455,1.00,4.000000,3.000000,3.0,2.445455,2,4.000000,2.445455,2.445455,3,1.9,1.000000,1,3.0,2.445455
20,Andhadhun,3.800000,3.792857,4.000000,3.00,4.000000,4.000000,4.5,3.792857,4,3.000000,3.792857,3.792857,3,5.0,2.000000,4,4.0,4.800000
21,Gully Boy,4.000000,2.000000,2.518182,3.00,2.518182,2.518182,3.0,2.518182,3,3.000000,2.518182,2.518182,2,2.7,1.000000,1,3.0,2.518182
22,Pathaan,2.192857,2.000000,3.500000,1.00,3.000000,1.000000,3.0,2.192857,2,3.000000,2.192857,2.192857,2,3.7,1.000000,1,2.0,2.500000
23,Jawan,2.281818,2.281818,2.281818,1.00,5.000000,2.281818,3.0,2.281818,2,3.000000,2.281818,2.281818,2,4.1,1.000000,1,2.0,1.000000
24,Animal,3.500000,0.000000,4.000000,0.01,4.000000,1.000000,3.0,2.150714,2,1.000000,2.150714,2.150714,3,3.6,1.000000,1,3.0,2.150714

# Primary Objective

1. Find similar people -  cross recommendation - People like you have like these movies too.
2. Find similar movies - People who like this movie also like that movie.

In [84]:
# Take average of each row & replace it with Nan for cleaning the data

rows = df.shape[0]

for i in range(0, rows) :
    movie_df = df.iloc[i]
    # print(movie_df, "\n")
    
    sum_val= 0
    count = 0
    for j in range(1, movie_df.shape[0]) :

        if not pd.isna(movie_df.iloc[j]):
            sum_val += movie_df.iloc[j]
            count += 1

    avg_val = sum_val / count

    for j in range(1, movie_df.shape[0]) :
        if pd.isna(movie_df.iloc[j]):
            df.iloc[i, j] = avg_val
    
df

,Movies_Name,SandeepGiri,Abhishek,Gurkaran,Madhuri,Venu,Gurpreet,Sanket,Yukta,Supriyo,Stuti,Priya,Harshita,Gokul,Charan,Bhaskar,Ankit,Aakash,Prabha
0,Titanic,4.000000,2.000000,4.000000,5.00,4.000000,2.000000,4.0,3.892857,4,4.000000,3.892857,3.892857,4,5.0,3.892857,5,4.0,3.500000
1,Matrix,4.800000,1.000000,3.000000,5.00,4.500000,4.500000,4.0,3.792308,4,3.792308,3.792308,3.792308,4,3.0,3.792308,3,4.5,4.000000
2,Jurasic Park,4.200000,2.000000,4.000000,4.00,3.000000,4.000000,5.0,3.442857,3,3.000000,3.442857,3.442857,4,2.0,3.442857,2,4.0,4.000000
3,Sholay,4.000000,5.000000,4.000000,4.00,5.000000,3.000000,4.0,3.786667,4,3.000000,3.786667,3.786667,3,1.0,3.000000,5,5.0,3.800000
4,Dilwale Dulhania Le Jayenge,3.800000,5.000000,4.000000,2.00,4.000000,1.000000,4.0,3.320000,3,3.500000,3.320000,3.320000,3,3.0,1.000000,5,4.0,3.500000
5,Mughal-e-Azam,2.833333,2.000000,2.000000,5.00,4.000000,1.000000,3.0,2.833333,3,2.833333,2.833333,2.833333,3,2.0,1.000000,4,4.0,2.833333
6,Deewaar,2.958333,4.000000,2.000000,2.00,3.000000,1.000000,3.0,2.958333,3,3.000000,2.958333,2.958333,3,4.0,2.958333,4,3.5,2.958333
7,Amar Akbar Anthony,3.076923,5.000000,2.000000,2.00,4.000000,2.000000,3.0,3.076923,3,3.000000,3.076923,3.076923,3,3.0,2.000000,4,4.0,3.076923
8,Lagaan,4.000000,5.000000,3.000000,4.00,5.000000,4.000000,5.0,4.000000,3,4.000000,4.000000,4.000000,3,5.0,2.000000,4,5.0,4.000000
9,Kabhi Khushi Kabhie Gham,3.800000,4.000000,3.000000,2.00,5.000000,3.000000,4.0,3.153333,2,4.000000,3.153333,3.153333,2,3.0,2.000000,3,3.0,3.500000
10,Kal Ho Naa Ho,3.800000,3.000000,3.000000,2.00,4.000000,2.000000,4.0,3.113333,2,4.000000,3.113333,3.113333,4,2.0,1.000000,3,5.0,3.900000
11,3 Idiots,4.000000,5.000000,4.000000,4.50,5.000000,4.000000,5.0,4.433333,4,5.000000,4.433333,4.433333,5,3.0,4.000000,5,5.0,4.000000
12,Dabangg,2.923077,3.000000,3.000000,2.00,5.000000,3.000000,3.0,2.923077,3,3.000000,2.923077,2.923077,4,4.0,1.000000,1,3.0,2.923077
13,Zindagi Na Milegi Dobara,4.000000,3.000000,4.000000,4.00,4.000000,4.500000,4.0,4.000000,3,5.000000,4.000000,4.000000,5,5.0,3.000000,3,4.5,4.000000
14,Barfi!,3.700000,3.000000,4.000000,4.00,3.000000,2.000000,3.0,3.121429,3,3.000000,3.121429,3.121429,3,3.0,3.000000,3,3.0,3.121429
15,Yeh Jawaani Hai Deewani,3.350000,3.000000,3.350000,3.00,4.000000,4.000000,3.0,3.350000,3,5.000000,3.350000,3.350000,5,3.2,1.000000,1,5.0,3.350000
16,PK,4.000000,4.000000,4.500000,3.00,3.000000,2.000000,3.0,3.257143,3,4.000000,3.257143,3.257143,4,4.1,1.000000,2,4.0,3.257143
17,Bajrangi Bhaijaan,2.653846,4.000000,3.000000,2.00,4.000000,1.000000,3.0,2.653846,3,3.000000,2.653846,2.653846,3,3.5,1.000000,1,3.0,2.653846
18,Dangal,4.069231,5.000000,4.000000,3.00,5.000000,4.000000,4.0,4.069231,4,5.000000,4.069231,4.069231,5,3.9,3.000000,2,5.0,4.069231
19,Padmaavat,2.445455,2.445455,2.445455,1.00,4.000000,3.000000,3.0,2.445455,2,4.000000,2.445455,2.445455,3,1.9,1.000000,1,3.0,2.445455
20,Andhadhun,3.800000,3.792857,4.000000,3.00,4.000000,4.000000,4.5,3.792857,4,3.000000,3.792857,3.792857,3,5.0,2.000000,4,4.0,4.800000
21,Gully Boy,4.000000,2.000000,2.518182,3.00,2.518182,2.518182,3.0,2.518182,3,3.000000,2.518182,2.518182,2,2.7,1.000000,1,3.0,2.518182
22,Pathaan,2.192857,2.000000,3.500000,1.00,3.000000,1.000000,3.0,2.192857,2,3.000000,2.192857,2.192857,2,3.7,1.000000,1,2.0,2.500000
23,Jawan,2.281818,2.281818,2.281818,1.00,5.000000,2.281818,3.0,2.281818,2,3.000000,2.281818,2.281818,2,4.1,1.000000,1,2.0,1.000000
24,Animal,3.500000,0.000000,4.000000,0.01,4.000000,1.000000,3.0,2.150714,2,1.000000,2.150714,2.150714,3,3.6,1.000000,1,3.0,2.150714

In [ ]:
# ChatGPT Code using Numpy for above -- for better performance

import numpy as np

values = df.iloc[:, 1:].to_numpy(dtype=float)

row_means = np.nanmean(values, axis=1)

# Find NaN positions and replace
inds = np.where(np.isnan(values))
values[inds] = np.take(row_means, inds[0])

# Put back into DataFrame
df.iloc[:, 1:] = values

In [96]:
arr = np.array(df['SandeepGiri'])

In [97]:
arr

array([4.        , 4.8       , 4.2       , 4.        , 3.8       ,
       2.83333333, 2.95833333, 3.07692308, 4.        , 3.8       ,
       3.8       , 4.        , 2.92307692, 4.        , 3.7       ,
       3.35      , 4.        , 2.65384615, 4.06923077, 2.44545455,
       3.8       , 4.        , 2.19285714, 2.28181818, 3.5       ])

In [110]:
def min_max_scaling(arr) :
    mini = np.min(arr)
    maxi = np.max(arr)

    # print("Maximum Value = ", maxi, "\nMinimum Value = ", mini)

    arr = (arr - mini) / (maxi - mini)

    return arr

In [ ]:
# min_max_scaling(arr)


for col in df.columns[1:]:
    arr = np.array(df[col].to_numpy(dtype=float))
    
    df[col] = min_max_scaling(arr)

df

,Movies_Name,SandeepGiri,Abhishek,Gurkaran,Madhuri,Venu,Gurpreet,Sanket,Yukta,Supriyo,Stuti,Priya,Harshita,Gokul,Charan,Bhaskar,Ankit,Aakash,Prabha
0,Titanic,0.693151,0.400000,0.800000,1.000000,0.597070,0.285714,0.50,0.763221,1.0,0.750000,0.763221,0.763221,0.666667,1.000,0.964286,1.00,0.666667,0.657895
1,Matrix,1.000000,0.200000,0.400000,1.000000,0.798535,1.000000,0.50,0.719171,1.0,0.698077,0.719171,0.719171,0.666667,0.500,0.930769,0.50,0.833333,0.789474
2,Jurasic Park,0.769863,0.400000,0.800000,0.799599,0.194139,0.857143,1.00,0.566079,0.5,0.500000,0.566079,0.566079,0.666667,0.250,0.814286,0.25,0.666667,0.789474
3,Sholay,0.693151,1.000000,0.800000,0.799599,1.000000,0.571429,0.50,0.716700,1.0,0.500000,0.716700,0.716700,0.333333,0.000,0.666667,1.00,1.000000,0.736842
4,Dilwale Dulhania Le Jayenge,0.616438,1.000000,0.800000,0.398798,0.597070,0.000000,0.50,0.512256,0.5,0.625000,0.512256,0.512256,0.333333,0.500,0.000000,1.00,0.666667,0.657895
5,Mughal-e-Azam,0.245662,0.400000,0.000000,1.000000,0.597070,0.000000,0.00,0.299051,0.5,0.458333,0.299051,0.299051,0.333333,0.250,0.000000,0.75,0.666667,0.482456
6,Deewaar,0.293607,0.800000,0.000000,0.398798,0.194139,0.000000,0.00,0.353812,0.5,0.500000,0.353812,0.353812,0.333333,0.750,0.652778,0.75,0.500000,0.515351
7,Amar Akbar Anthony,0.339094,1.000000,0.000000,0.398798,0.597070,0.285714,0.00,0.405766,0.5,0.500000,0.405766,0.405766,0.333333,0.500,0.333333,0.75,0.666667,0.546559
8,Lagaan,0.693151,1.000000,0.400000,0.799599,1.000000,0.857143,1.00,0.810160,0.5,0.750000,0.810160,0.810160,0.333333,1.000,0.333333,0.75,1.000000,0.789474
9,Kabhi Khushi Kabhie Gham,0.616438,0.800000,0.400000,0.398798,1.000000,0.571429,0.50,0.439241,0.0,0.750000,0.439241,0.439241,0.000000,0.500,0.333333,0.50,0.333333,0.657895
10,Kal Ho Naa Ho,0.616438,0.600000,0.400000,0.398798,0.597070,0.285714,0.50,0.421717,0.0,0.750000,0.421717,0.421717,0.666667,0.250,0.000000,0.50,1.000000,0.763158
11,3 Idiots,0.693151,1.000000,0.800000,0.899800,1.000000,0.857143,1.00,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,0.500,1.000000,1.00,1.000000,0.789474
12,Dabangg,0.280084,0.600000,0.400000,0.398798,1.000000,0.571429,0.00,0.338367,0.5,0.500000,0.338367,0.338367,0.666667,0.750,0.000000,0.00,0.333333,0.506073
13,Zindagi Na Milegi Dobara,0.693151,0.600000,0.800000,0.799599,0.597070,1.000000,0.50,0.810160,0.5,1.000000,0.810160,0.810160,1.000000,1.000,0.666667,0.50,0.833333,0.789474
14,Barfi!,0.578082,0.600000,0.800000,0.799599,0.194139,0.285714,0.00,0.425263,0.5,0.500000,0.425263,0.425263,0.333333,0.500,0.666667,0.50,0.333333,0.558271
15,Yeh Jawaani Hai Deewani,0.443836,0.600000,0.540000,0.599198,0.597070,0.857143,0.00,0.525399,0.5,1.000000,0.525399,0.525399,1.000000,0.550,0.000000,0.00,1.000000,0.618421
16,PK,0.693151,0.800000,1.000000,0.599198,0.194139,0.285714,0.00,0.484719,0.5,0.750000,0.484719,0.484719,0.666667,0.775,0.000000,0.25,0.666667,0.593985
17,Bajrangi Bhaijaan,0.176818,0.800000,0.400000,0.398798,0.597070,0.000000,0.00,0.220419,0.5,0.500000,0.220419,0.220419,0.333333,0.625,0.000000,0.00,0.333333,0.435223
18,Dangal,0.719705,1.000000,0.800000,0.599198,1.000000,0.857143,0.50,0.840489,1.0,1.000000,0.840489,0.840489,1.000000,0.725,0.666667,0.25,1.000000,0.807692
19,Padmaavat,0.096887,0.489091,0.178182,0.198397,0.597070,0.571429,0.00,0.129124,0.0,0.750000,0.129124,0.129124,0.333333,0.225,0.000000,0.00,0.333333,0.380383
20,Andhadhun,0.616438,0.758571,0.800000,0.599198,0.597070,0.857143,0.75,0.719412,1.0,0.500000,0.719412,0.719412,0.333333,1.000,0.333333,0.75,0.666667,1.000000
21,Gully Boy,0.693151,0.400000,0.207273,0.599198,0.000000,0.433766,0.00,0.160985,0.5,0.500000,0.160985,0.160985,0.000000,0.425,0.000000,0.00,0.333333,0.399522
22,Pathaan,0.000000,0.400000,0.600000,0.198397,0.194139,0.000000,0.00,0.018463,0.0,0.500000,0.018463,0.018463,0.000000,0.675,0.000000,0.00,0.000000,0.394737
23,Jawan,0.034122,0.456364,0.112727,0.198397,1.000000,0.366234,0.00,0.057436,0.0,0.500000,0.057436,0.057436,0.000000,0.775,0.000000,0.00,0.000000,0.000000
24,Animal,0.501370,0.000000,0.800000,0.000000,0.597070,0.000000,0.00,0.000000,0.0,0.000000,0.000000,0.000000,0.333333,0.650,0.000000,0.00,0.333333,0.302820

In [112]:
SandeepArray = np.array(df['SandeepGiri'])
CharanArray = np.array(df['Charan'])

cos_sim = np.dot(SandeepArray, CharanArray) / (np.linalg.norm(SandeepArray) * np.linalg.norm(CharanArray))

print("Cosine Similarity:", cos_sim)

Cosine Similarity: 0.8206606679818685